### ISSUE TITLE
firebase config 정보가 노출되어있는데 괜찮을까요?

### ISSUE THREAD

**Issue by with-key** [sasha1107/pwa-nextjs#1]

**Comment by sasha1107** [comment]
일반적인 API Key와 다르게 백엔드 리소스에 대한 액세스를 제어하는데 사용되지 않아, 꼭 env로 보호하지 않아도 된다는 [firebase 문서](https://firebase.google.com/docs/projects/api-keys?hl=ko)를 한 번 믿어보기로 했습니다🫨.
환경 변수로 노출되지 않도록 하는 것이 가장 안전한 방법일 것 같기는 합니다 🧐 
이러한 좋은 글도 발견하여 공유 드려봅니다!! [🤔 Firebase API Key를 공개하는 것이 안전합니까?](https://haranglog.tistory.com/25)
확인해주셔서 감사합니다🙇‍♂️🙇‍♂️

**Comment by with-key** [comment]
그렇군요! 답변 감사합니다. 🙇‍♂️
